### PR TITLE
Bug 1729750 - Support speech-dispatcher in Snap

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Review by seb128 — APPROVED** [review]
Thanks. We will need to SRU the systemd socket activation changes for that to work but at least we get one step closer

**Comment by lissyx** [comment]
:+1: Let me know if I need to send PR for `core22` and other branches as well.

**Comment by seb128** [comment]
Yes please PR core22 so we don't forget to cherrypick it there once tested in nightly

**Comment by lissyx** [comment]
@seb128 gentle ping, what's the status of the SRU ? Can we merge this?

**Comment by seb128** [comment]
The SRU is in the review queue
https://bugs.launchpad.net/ubuntu/+source/speech-dispatcher/+bug/1991022

Did you do the merge request for core22?

**Comment by lissyx** [comment]
yes #13

**Pull request merged**
