### PR TITLE
Updated for core22 and gnome-42-2204

### PR DESCRIPTION
**Pull request by kenvandine**

### CODE REVIEW

**Review by mkaply — COMMENTED** [review]
Why the change from SNAPCRAFT to CRAFT? Seems like that's a lot of the changes in the patch.

**Comment by kenvandine** [comment]
> Why the change from SNAPCRAFT to CRAFT? Seems like that's a lot of the changes in the patch.

There were some significant changes in snapcraft when building a snap based on core22.  Under the covers it was refactored to be able to build other artifacts, not just snaps.  So some names were made more generic.

**Comment by Darkspirit** [comment]
https://discourse.ubuntu.com/t/problems-with-intel-iris-xe-gpu-hardware-video-acceleration-in-22-04/34849
and https://bugzilla.mozilla.org/show_bug.cgi?id=1760941
indicate that this PR needs to be merged for [Firefox 115 Beta and Stable](https://whattrainisitnow.com/calendar/) to have an intel-media-driver version that supports Iris Xe.
VAAPI has been enabled by default for Intel: https://bugzilla.mozilla.org/show_bug.cgi?id=1777430

**Comment by antgel** [comment]
Lovely to see some action on this branch. I don't have the details to hand, but I believe this upgrade will assist with hardware acceleration for certain video codecs and perhaps Google Meet, so I'm quite excited about it. Is there an IRC channel or something I can join to get more into the pulse of development of this upgrade? 

Edit: I just found https://discourse.ubuntu.com/t/call-for-testing-firefox-snap-upgrading-base-from-core20-to-core22/36746 :)
Edit 2: I found the details, it was to do with an updated `intel-media-driver` https://bugzilla.mozilla.org/show_bug.cgi?id=1760941.

I'll try it out now, and take feedback to Discourse, thanks!

**Comment by bandali** [comment]
Good timing @antgel, as we're now ready to merge this. :slightly_smiling_face:

**Pull request merged**
