### PR TITLE
Add mount-observe plug for https://bugzilla.mozilla.org/1934713

### PR DESCRIPTION
**Pull request by alexmurray**
Silences syslog messages when spawning the file open dialog etc

Signed-off-by: Alex Murray <alex.murray@canonical.com>

### CODE REVIEW

**Review by kenvandine — APPROVED** [review]
Looks good!

**Review by seb128 — APPROVED** [review]
Thanks. Unsure if that's something specific to firefox or a GTK fileselector thing where we would benefit from trying to fix it at the desktop interface level?

I'm going to merge that change for now since it's an improvement for firefox in any case. Will you also send us a request to auto-connect it or should we do that?

**Comment by alexmurray** [comment]
Thanks

> Will you also send us a request to auto-connect it or should we do that?

I think that is best coming from the publisher ;)

**Comment by soumyaDghosh** [comment]
> Unsure if that's something specific to firefox or a GTK fileselector thing where we would benefit from trying to fix it at the desktop interface level?

That error log is specific for GTK FilePicker.

**Pull request merged**
