### PR TITLE
[Beta] Stage opensc-pkcs11.so and layout it.

### PR DESCRIPTION
**Pull request by nteodosio**

### CODE REVIEW

**Review by seb128 — APPROVED** [review]
Thanks, makes sense to move that forward and merge in beta now. @bandali0 do you agree?

**Comment by nteodosio** [comment]
A note I forgot to add is that this is a confirmed fix from the affected users.

@bandali0, when you review this, can you also review #86 together?

**Review by bandali — CHANGES_REQUESTED** [review]
hey @nteodosio thanks for the PRs and sorry for the slow reply here. Firefox snap beta and stable are still on core22, so I believe we have to use the old environment variable names here, such as `$CRAFT_ARCH_TRIPLET`.

**Comment by nteodosio** [comment]
Hey @bandali0, no problem.

Judging by https://snapcraft.io/docs/parts-environment-variables#heading--locating-directories-core22 the variable is there in core22 too.

**Comment by seb128** [comment]
Indeed according to the documentation the variable has been added to core22

**Pull request merged**
