### PR TITLE
Bug1901703 unify desktop files

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by lissyx** [comment]
green from https://treeherder.mozilla.org/jobs?repo=try&revision=83e0aa3b32018b2bfb0bb017757d944bdc26fc77

**Comment by lissyx** [comment]
try on the latest version: https://treeherder.mozilla.org/jobs?repo=try&revision=d1bb2c1bb56525b8068604c45767b5d8b845aaf4

**Comment by lissyx** [comment]
@bandali0 could you please have a look ?

**Comment by lissyx** [comment]
uptodate try: https://treeherder.mozilla.org/jobs?repo=try&revision=4621f7b8a2aa419b8d5b18dea57f6a494b0cf707

**Review by bandali — APPROVED** [review]
From some quick testing this looks good to me. So, with the upstream change having been landed, I'm merging this into `nightly`.

Thank you!

**Pull request merged**
